#!/bin/bash

TITLE="Files of $HOSTNAME"
RIGHT_NOW=$(date +"%x - %H:%M")


function wrong_parameter {
        echo "Wrong parameter"
        echo "Use \"html -h\" for help"
} 1>&2

help()
{
	echo "html [directory|file] | -h"
        echo -e "\t-h show help"
        echo -e "\t-a sort ascending (by file name)"
        echo -e "\t-d sort descending (by file name)"
        exit 1
}

create_dir()
{
        mkdir ~/File_list
}

download_css()
{
        wget -P ~/File_list https://raw.githubusercontent.com/Domikado5/bash-script-template/master/style.css
} &> /dev/null

create_html()
{
        touch ~/File_list/index.html
}

SORT=0

while [ $1 ];
do
        if [ -d $1 ]
        then DIRECTORY+=($1); shift
        elif [ -f $1 ]
        then FILE+=($1); shift
        elif [[ $1 == "-h" ]]
        then help; exit 1
        elif [[ $1 == "-a" ]] && [[ $SORT -eq 0 ]]
        then SORT=1; shift
        elif [[ $1 == "-d" ]] && [[ $SORT -eq 0 ]]
        then SORT=2; shift
        elif [[ $1 =~ -[^h] ]]
        then wrong_parameter; exit 2
        else CUSTOM+=($1); shift
        fi
done

echo "Your directories: $DIRECTORY"
echo "Your files: $FILE"
echo "Your custom extensions: $CUSTOM"
echo "Sort type: $SORT"


### check if save directory exist
if [ ! -d ~/File_list ]; then
        create_dir
fi

### check if style.css exist
if [ ! -f ~/File_list/style.css ]; then
        echo "Pobieranie pliku CSS"
        download_css
        echo "Pobrano"
fi

### check if index.html exist
if [ ! -f ~/File_list/index.html ]; then
        create_html
fi

echo "<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <link rel=\"stylesheet\" href=\"/home/justdodo/Documents/bash-script-template/style.css\"> 
    <title>$TITLE</title>
    </head>
<body>
    <nav>
        <h1>$TITLE</h1>
        <h1>$RIGHT_NOW</h1>
    </nav>" > ~/File_list/index.html


pictures() {
        echo "    <section>
        <h1>Images</h1>" 1>> ~/File_list/index.html
        case $SORT in
        0)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.gif -o -iname \*.jpeg \) -printf "<div class=\"element\"><div class=\"min\"><img src=\"%p\" alt=\"%f\"></div><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" 1>> ~/File_list/index.html
        ;;
        1)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.gif -o -iname \*.jpeg \) -printf "%f ~<div class=\"element\"><div class=\"min\"><img src=\"%p\" alt=\"%f\"></div><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        2)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.gif -o -iname \*.jpeg \) -printf "%f ~<div class=\"element\"><div class=\"min\"><img src=\"%p\" alt=\"%f\"></div><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort -r | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        esac
        echo "</section>" 1>> ~/File_list/index.html
}

music() {
        echo "    <section>
        <h1>Music</h1>" 1>> ~/File_list/index.html
        case $SORT in
        0)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.mp3 -o -iname \*.wav -o -iname \*.mp4 -o -iname \*.flac \) -printf "<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" 1>> ~/File_list/index.html
        ;;
        1)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.mp3 -o -iname \*.wav -o -iname \*.mp4 -o -iname \*.flac \) -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        2)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.mp3 -o -iname \*.wav -o -iname \*.mp4 -o -iname \*.flac \) -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort -r | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        esac
        echo "</section>" 1>> ~/File_list/index.html
}

documents() {
        echo "    <section>
        <h1>Documents</h1>" 1>> ~/File_list/index.html
        case $SORT in
        0)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.pdf -o -iname \*.doc -o -iname \*.odt \) -printf "<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" 1>> ~/File_list/index.html
        ;;
        1)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.pdf -o -iname \*.doc -o -iname \*.odt \) -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        2)
        find ${DIRECTORY[@]} ${FILE[@]} -type f \( -iname \*.pdf -o -iname \*.doc -o -iname \*.odt \) -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort -r | cut -d "~" -f 2- 1>> ~/File_list/index.html
        ;;
        esac
        echo "</section>" 1>> ~/File_list/index.html
}

custom() {
        for ext in $CUSTOM
        do
                echo "    <section>
                <h1>$ext</h1>" 1>> ~/File_list/index.html
                case $SORT in
                0)
                find ${DIRECTORY[@]} ${FILE[@]} -type f -iname "*.$ext" -printf "<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" 1>> ~/File_list/index.html
                ;;
                1)
                find ${DIRECTORY[@]} ${FILE[@]} -type f -iname "*.$ext" -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort | cut -d "~" -f 2- 1>> ~/File_list/index.html
                ;;
                2)
                find ${DIRECTORY[@]} ${FILE[@]} -type f -iname "*.$ext" -printf "%f ~<div class=\"element\"><p>Filename:</p><div class=\"name\">%f</div><p>Modified:</p><div class=\"mod\">%Td.%Tm.%TY %TH:%TM</div><p>Source:</p><div class=\"source\">%p</div><p>Attachment:</p><a href=\"file://%p\">Click me</a></div>\n" | sort -r | cut -d "~" -f 2- 1>> ~/File_list/index.html
                ;;
                esac
                echo "</section>" 1>> ~/File_list/index.html
        done
}

pictures
music
documents
custom

echo "</body>
</html>" 1>> ~/File_list/index.html

firefox ~/File_list/index.html